FROM java:8

EXPOSE 8084

ADD target/airport-checking-service-0.0.1-SNAPSHOT.jar airport-checking-service-0.0.1-SNAPSHOT.jar

ENTRYPOINT ["java", "-jar", "airport-checking-service-0.0.1-SNAPSHOT.jar"]